- .travis.yml
- conference_scheduler/parameters.py
- conference_scheduler/resources.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/test_parameters.py
Also:
- Added sessions in the test fixtures.
- Added some specific numpy tests that check that the constraints work as expected.
- Modified `parameters.constraints` to deal with constraints that take different arguments.
> Add constraint for tags

- conference_scheduler/parameters.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/test_parameters.py
- conference_scheduler/tests/test_scheduler.py
- requirements.txt
- setup.cfg
- setup.py
> Validation of existing solution

- conference_scheduler/parameters.py
- conference_scheduler/resources.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/test_parameters.py
- conference_scheduler/tests/test_scheduler.py
> Report constraint violations for invalid solutions

- conference_scheduler/lp_problem/constraints.py
- conference_scheduler/lp_problem/utils.py
- conference_scheduler/parameters.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/lp_problem/test_constraints.py
- conference_scheduler/tests/lp_problem/test_utils.py
- conference_scheduler/tests/test_parameters.py
- conference_scheduler/tests/test_scheduler.py
> Validation of a schedule

- conference_scheduler/lp_problem/constraints.py
- conference_scheduler/lp_problem/utils.py
- conference_scheduler/resources.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/lp_problem/test_constraints.py
- conference_scheduler/tests/lp_problem/test_utils.py
- conference_scheduler/tests/test_scheduler.py
This ensures that all constraints and objective functions now just take
slots and events as arguments.
> Move sessions to slots.

- conference_scheduler/resources.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/test_scheduler.py
- conference_scheduler/tests/test_validator.py
- conference_scheduler/validator.py
and get coverage to 100%
Fixes #23
> Remove ad-hoc constraints

- .travis.yml
- conference_scheduler/lp_problem/__init__.py
- conference_scheduler/resources.py
- conference_scheduler/tests/conftest.py
- conference_scheduler/tests/test_scheduler.py
- docs/tutorial/index.rst
- doctests.py
This is very much a moving target but shows how a conference could be scheduled with the tool as is.
I think it highlights  a couple of things that can be removed from the data structures (we're duplicating things with the rooms which I'm not sure are necessary) but hopefully this tutorial helps with our discussion going forward. :)
> Add a tutorial

- conference_scheduler/lp_problem/objective_functions.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/lp_problem/test_objective_functions.py
- conference_scheduler/tests/test_scheduler.py
- docs/tutorial/index.rst
This closes #4 
Note I've also added a section to the tutorial for it and when I did I noticed an error I made in the earlier tutorial section (I had all the unavailability variables be pointers to the same list, so modifying one modified them all). I've fixed that which modifies the example solution schedules in there slighty.
> Optimise for least change

- docs/tutorial/index.rst
We have this specifically mentioned in the README so thought it was
worth having here.
> Add validation section to tutorial.

- conference_scheduler/lp_problem/utils.py
- conference_scheduler/tests/lp_problem/test_constraints.py
- conference_scheduler/tests/lp_problem/test_utils.py
- conference_scheduler/tests/test_scheduler.py
- conference_scheduler/tests/test_validator.py
- docs/tutorial/index.rst
We had said that we would just include this in the unavailability but
that seems silly as we can capture it directly (it's essentially a
generic form of unavailability).
> Add constraint on duration in to availability.

- conference_scheduler/lp_problem/constraints.py
- conference_scheduler/lp_problem/utils.py
- conference_scheduler/scheduler.py
> Use lpsum function when solving the schedule

- conference_scheduler/scheduler.py
- conference_scheduler/tests/test_scheduler.py
- docs/howtos/index.rst
- docs/howtos/use_different_solver.rst
> Add ability to pass another solver.

- conference_scheduler/resources.py
- conference_scheduler/scheduler.py
- conference_scheduler/tests/test_scheduler.py
- docs/tutorial/index.rst
> Showing differences between schedules

- conference_scheduler/lp_problem/constraints.py
- conference_scheduler/lp_problem/utils.py
- setup.cfg
> Use lpsum instead of plain addition for constraints

- conference_scheduler/scheduler.py
- conference_scheduler/tests/test_scheduler.py
- docs/tutorial/index.rst
Closes #58
I haven't sorted the lists, leaving that to the user. I've also adjusted the docs.
> Return the outputs as lists

- conference_scheduler/scheduler.py
- conference_scheduler/tests/test_scheduler.py
- docs/background/mathematical_model.rst
- docs/howtos/index.rst
- docs/howtos/mathematical_representation.rst
- docs/tutorial/index.rst
> Adds a how to for going between array and schedule

- docs/tutorial/index.rst
- src/conference_scheduler/lp_problem/constraints.py
- src/conference_scheduler/resources.py
- tests/test_resources.py
> Use properties for event.tags and event.unavailability

- .gitignore
- .travis.yml
- docs/index.rst
- docs/reference/index.rst
- docs/reference/resources.rst
- docs/reference/resources.txt
- docs/reference/scheduler.rst
- docs/reference/scheduler.txt
- reference_docs/build_reference.py
- reference_docs/conf.py
- reference_docs/index.rst
- src/conference_scheduler/resources.py
* Adds a `reference_docs` directory which contains a script to build the reference docs
* Adds stub files in `docs/reference` to import the content built by the above
* Adds doctests and doc building to travis config
> Reference Docs

- requirements.txt
> Add undocumented PyYAML dependency

- src/conference_scheduler/scheduler.py
- tests/test_scheduler.py
> Add solver and kwargs arguments to scheduler.array

- src/conference_scheduler/heuristics/simulated_annealing.py
- tests/heuristics/test_simulated_annealing.py
I was resetting the best energy incorrectly. That should only be reset
if the candidate is better.
> Fix an error in the simulated annealing.

- docs/howto/obtain_mathematical_representation.rst
- docs/tutorial/index.rst
- src/conference_scheduler/lp_problem/utils.py
- tests/conftest.py
- tests/test_scheduler.py
> Remove all use of strings for Slot.starts_at

- src/conference_scheduler/scheduler.py
- src/conference_scheduler/validator.py
- tests/test_scheduler.py
This allows for a given solution to be further optimised using a
heuristic approach.
> Add ability to use heuristic from given solution.
